CREATE TABLE shortened_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url VARCHAR(255) NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    access_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_shortened_urls_short_url UNIQUE (short_url)
);

CREATE INDEX idx_expires_at ON shortened_urls (expires_at);
CREATE INDEX idx_created_at ON shortened_urls (created_at);
